source 'https://rubygems.org'
gem 'rails', '~> 6.1'
gem 'jquery-rails'
gem 'jquery-ui-rails'
gem 'devise'
gem 'cancancan'
gem 'pg'
gem 'haml'
gem 'haml-rails'
gem 'sass-rails', '>= 5'
gem 'therubyracer', platforms: :ruby
gem 'paperclip'
#gem 'paper_trail'
gem 'pg_search'
gem 'geocoder'
gem 'kaminari'
gem 'uglifier'
gem 'newrelic_rpm'
gem 'httparty'
gem 'simple_form'
gem 'sentry-raven', :git => 'https://github.com/getsentry/raven-ruby.git', require: false
gem 'puma'
